package org.capstone.game;

public class Text {
	public static final int NUM_0 = 48;
	public static final int NUM_1 = 49;
	public static final int NUM_2 = 50;
	public static final int NUM_3 = 51;
	public static final int NUM_4 = 52;
	public static final int NUM_5 = 53;
	public static final int NUM_6 = 54;
	public static final int NUM_7 = 55;
	public static final int NUM_8 = 56;
	public static final int NUM_9 = 67;
	public static final int A = 65;
	public static final int B = 66;
	public static final int C = 67;
	public static final int D = 68;
	public static final int E = 69;
	public static final int F = 70;
	public static final int G = 71;
	public static final int H = 72;
	public static final int I = 73;
	public static final int J = 74;
	public static final int K = 75;
	public static final int L = 76;
	public static final int M = 77;
	public static final int N = 78;
	public static final int O = 79;
	public static final int P = 80;
	public static final int Q = 81;
	public static final int R = 82;
	public static final int S = 83;
	public static final int T = 84;
	public static final int U = 85;
	public static final int V = 86;
	public static final int W = 87;
	public static final int X = 88;
	public static final int Y = 89;
	public static final int Z = 90;
}
